### PR TITLE
Bump depandencies to avoid vulnerabilities

### PR DESCRIPTION
**Pull request by AlexZhenWang**
Passed `yarn audit` and `npm audit`. 

I noticed this project has both package-lock.json and yarn.lock. From the README, seems like we are using npm in this project, do we want to remove yarn.lock?

I tested this project by running `npm test`, may I ask whether this is enough?

### CODE REVIEW

**Comment by jordy25519** [comment]
@AlexZhenWang can you push this again? (I've updated circleci settings so it should build this PR)

**Comment by AlexZhenWang** [comment]
> @AlexZhenWang can you push this again? (I've updated circleci settings so it should build this PR)

Yep. Sure

**Comment by AlexZhenWang** [comment]
> @AlexZhenWang can you push this again? (I've updated circleci settings so it should build this PR)
re-pushed

**Review by jordy25519 — APPROVED** [review]
TY 👍

**Comment by AlexZhenWang** [comment]
> TY 👍

Thanks, @holygits !

**Pull request merged**
